 高斯贝叶斯

In [7]:
import numpy as np

X = np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
Y = np.array([1,1,1,2,2,2])

from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X,Y)
clf.predict([[-2,4]] )


array([2])

多项式贝叶斯

In [11]:
import numpy as np
X = np.random.randint(5,size=(6,100))
y = np.array([1,2,3,4,5,6])
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X,y)
clf.predict([X[5]])

array([6])

伯努利贝叶斯

In [14]:
import numpy as np
X = np.random.randint(2,size=(6,100))
Y = np.array([1,2,3,4,5,6])
from sklearn.naive_bayes import BernoulliNB
clf=BernoulliNB()
clf.fit(X,Y)
clf.predict([X[1]])

array([2])

In [15]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn import datasets
from sklearn.metrics import confusion_matrix
iris = datasets.load_iris()
gnb = GaussianNB()
mnb = MultinomialNB()

y_pred_gnb = gnb.fit(iris.data,iris.target).predict(iris.data)
cnf_matrix_gnb = confusion_matrix(iris.target,y_pred_gnb)
print(cnf_matrix_gnb)
y_pred_mnb = mnb.fit(iris.data,iris.target).predict(iris.data)
cnf_matrix_mnb = confusion_matrix(iris.target,y_pred_mnb)
print(cnf_matrix_mnb)

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]
[[50  0  0]
 [ 0 46  4]
 [ 0  3 47]]


In [30]:
(0.63*0.98)/(0.68+0.93)*2

0.7669565217391303

In [19]:
set([x for x in range(2,100) all if x % y for y in range(2,x) ])

SyntaxError: invalid syntax (<ipython-input-19-9fc033476c4c>, line 1)