In [12]:
import numpy as np
a = np.empty((2,3),np.int)
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
def func(i):
    return i%4+1
a = np.fromfunction(func,(2,))
def func2(i,j):
    return (i+1)*(j+1)
b = np.fromfunction(func2,(9,9))
b

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

In [32]:
a = np.arange(10)
a[5]
a[3:5]
a[-1]
a[2:4] = 100,101
a[1:-1:2]


In [35]:
x = np.arange(10,1,-1)
x[[3,3,1,8]]
b = x[np.array([3,3,-3,8])]
b = [[3,5,1]]
x[x>4]

array([10,  9,  8,  7,  6,  5])

In [44]:
a = np.arange(0,60,10).reshape(-1,1)+np.arange(0,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [53]:
a[(1,2,3),  ]

IndexError: too many indices for array