### 3.1 对数值进行取整

使用内建的round(value, ndigits)函数即可

In [2]:
print(round(1.23, 1))
print(round(1.27, 1))
print(round(-1.27, 1))

1.2
1.3
-1.3


当某个值恰好等于两个整数间的一半，取整操作会取到离该值最接近的那个偶数上。如1.5，2.5这样的值都会取整到2。  
传递给round()的参数ndigits可以是负数，这样会相应地取整到十位、百位、千位等。  

In [3]:
print(round(1224, -2))

1200


### 3.2 执行精确地小数计算

如果期望浮点数运算得到更高地精度，并愿意为此牺牲掉一些性能，可以使用decimal模块。

In [4]:
from decimal import Decimal
a = Decimal('4.2')
b = Decimal('2.1')
print(a + b)

6.3


decimal模块地主要功能是允许控制计算过程地各个方面，包括数字的位数和四舍五入等。  
需要创建一个上下文环境然后修改其设定。

In [6]:
from decimal import localcontext
a = Decimal('2.0')
b = Decimal('3.5')
print(a/b)
with localcontext() as ctx:
    ctx.prec = 3
    print(a/b)

0.5714285714285714285714285714
0.571


### 3.3 对数值做格式化输出

要对一个单独的数值做格式化输出，使用内建的format()函数就可以了。

In [9]:
x = 1234.5678
# Two decimal places of accuracy
print(format(x, '0.2f'))
# Right justified in 10 chars, one-digit accuracy
print(format(x, '>10.1f'))
# Left justified
print(format(x, '<10.1f'))
# Centered
print(format(x, '^10.1f'))
# Inclusion of thousands separator
print(format(x, ','))
print(format(x, '0,.1f'))
# 科学记数法
print(format(x, '0.2E'))

1234.57
    1234.6
1234.6    
  1234.6  
1,234.5678
1,234.6
1.23E+03


同样的格式也可用于字符串.format()方法中。

In [11]:
'The value is {:0,.2f}'.format(x)

'The value is 1,234.57'

也可用字符串的translate()方法交换不同的分隔字符。

In [12]:
swap_separators = {ord('.'):',', ord(','):'.'}
format(x, ',').translate(swap_separators)

'1.234,5678'

### 3.4 同二进制、八进制和十六进制数打交道

要将一个整数转换为二进制、八进制、十六进制的文本字符串形式，只需要分别使用内建的  
bin()、oct()、和hex()函数即可。

In [13]:
x = 123
print(bin(x))
print(oct(x))
print(hex(x))

0b1111011
0o173
0x7b


如果不希望出现0b、0o、0x这样的前缀，可以使用format()函数。

In [15]:
print(format(x, 'b'))
print(format(x, 'o'))
print(format(x, 'x'))

1111011
173
7b


要将字符串形式的整数转换为不同的进制，只需要使用int()函数配合适当的进制即可。

In [16]:
int('4d2', 16)

1234

### 3.5 从字节串中打包和解包大整数

假设程序需要处理一个有着16个元素的字节串，其中保存着一个128位的整数。  
要将字节解释位整数，可以使用int.from_bytes(),然后指定字节序即可。

In [19]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [20]:
len(data)

16

In [21]:
int.from_bytes(data, 'little')

69120565665751139577663547927094891008

In [22]:
int.from_bytes(data, 'big')

94522842520747284487117727783387188

要将一个大整数重新转换成字节串，可以使用int.to_bytes()方法，只要指定字节数和字节序即可。

In [23]:
x = 1582157818951258155238095353234998

In [24]:
x.to_bytes(16, 'big')

b'\x00\x00N\x01\xa3\xa1\xd5\xee\x13\x13\xe1\x94\x9aKF6'

In [25]:
x.to_bytes(16, 'little')

b'6FK\x9a\x94\xe1\x13\x13\xee\xd5\xa1\xa3\x01N\x00\x00'

如果尝试将一个整数打包成字节串，但字节大小不合适，就会得到一个错误信息。  
可以使用int.bit_length()方法来确定需要用到多少位才能保存这个值。

In [26]:
y = 523 ** 23
print(y)

335381300113661875107536852714019056160355655333978849017944067


In [27]:
y.to_bytes(16, 'little')

OverflowError: int too big to convert

In [30]:
y.bit_length()

208

In [34]:
nbytes, rem = divmod(y.bit_length(), 8)
if rem:
    nbytes += 1

In [35]:
y.to_bytes(nbytes, 'little')

b'\x03X\xf1\x82iT\x96\xac\xc7c\x16\xf3\xb9\xcf\x18\xee\xec\x91\xd1\x98\xa2\xc8\xd9R\xb5\xd0'

### 3.6 复数运算

In [36]:
a = complex(2,4)
b = 3 - 5j
print(a, b)

(2+4j) (3-5j)


In [37]:
print(a.real, a.imag, a.conjugate())

2.0 4.0 (2-4j)


常见得算数运算操作都适用于复数。  
但如果要执行有关复数得函数操作，如求正弦，平方根等，可以使用cmath模块。

In [38]:
import cmath
cmath.sin(a)

(24.83130584894638-11.356612711218174j)

### 3.7 处理无穷大和NaN

In [39]:
a = float('inf')
b = float('-inf')
c = float('nan')
print(a,b, c)

inf -inf nan


In [42]:
# 检测
import math
print(math.isinf(a))
print(math.isnan(c))

True
True


In [43]:
# 无穷大值在数学计算中会传播
print(a + 45, a*10, 20/a)

inf inf 0.0


In [44]:
# nan会通过所有操作传播,并且不会报错
print(c * 2)

nan


In [45]:
# nan在比较时从不会被判定为相等
# 因此唯一安全检测NaN的方法是使用math.isnan()
d = float('nan')
c == d

False

### 3.8 分数的计算

fractions模块可以用来处理涉及分数的数学计算问题。

In [46]:
from fractions import Fraction
a = Fraction(5, 4)
b = Fraction(7, 16)
print(a + b)

27/16


In [47]:
c = a * b
print(c)
# Getting numerator/denominator
print(c.numerator)
print(c.denominator)

35/64
35
64


In [48]:
# Converting to a float
print(float(c))
# Convert a float to a fraction
x = 3.75
y = Fraction(*x.as_integer_ratio())
print(y)

0.546875
15/4


### 3.9 处理大型数组的计算

假设我们需要对大型的数据集比如数组或网格（grid)进行计算。  
对于任何设计数组的计算密集型任务，可以是用Numpy库。

In [50]:
x = [1, 2, 3, 4]
y = [5, 6, 6, 8]
print(x * 2, '\n', x + y)

[1, 2, 3, 4, 1, 2, 3, 4] 
 [1, 2, 3, 4, 5, 6, 6, 8]


In [52]:
import numpy as np
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
print(ax * 2, ax + ay, ax * ay)

[2 4 6 8] [ 6  8 10 12] [ 5 12 21 32]


In [53]:
# 数组还可以用于函数
def f(x):
    return 3*x**2 - 2*x + 7

print(f(ax))

[ 8 15 28 47]


In [54]:
a = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
# Select row 1
print(a[1])
# Select column 1
print(a[:,1])

[5 6 7 8]
[ 2  6 10]


In [56]:
# Select a subregion and change it
print(a[1:3, 1:3])
a[1:3, 1:3] += 10
print(a)

[[ 6  7]
 [10 11]]
[[ 1  2  3  4]
 [ 5 16 17  8]
 [ 9 20 21 12]]


In [57]:
# Broadcast a row vector across an operation on all rows
print(a + [100, 101, 102, 103])

[[101 103 105 107]
 [105 117 119 111]
 [109 121 123 115]]


In [58]:
# Conditional assignment on an array
np.where(a < 10, a, 10)

array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])

### 3.10 矩阵和线性代数的计算

假如我们要执行矩阵和线性代数方面的操作，如矩阵乘法，求行列式，解线性方程等。  
Numpy库中有个matrix对象，和array有些类似，但在计算时遵循线性代数规则。

In [59]:
import numpy as np
m = np.matrix([[1, -2, 3],
              [0, 4, 5],
              [7, 8, -9]])
print(m)

[[ 1 -2  3]
 [ 0  4  5]
 [ 7  8 -9]]


In [60]:
# Return transpose
print(m.T)

[[ 1  0  7]
 [-2  4  8]
 [ 3  5 -9]]


In [61]:
# Return inverse
print(m.I)

[[ 0.33043478 -0.02608696  0.09565217]
 [-0.15217391  0.13043478  0.02173913]
 [ 0.12173913  0.09565217 -0.0173913 ]]


In [62]:
# Create a vector and multiply
v = np.matrix([[2], [3], [4]])
print(v)
print(m * v)

[[2]
 [3]
 [4]]
[[ 8]
 [32]
 [ 2]]


更多的操作可在numpy.linalg子模块中找到。

In [63]:
import numpy.linalg

# Determinant
print(numpy.linalg.det(m))

-230.0


In [64]:
# Eigenvalues
print(numpy.linalg.eigvals(m))

[-13.11474312   2.75956154   6.35518158]


In [66]:
# Solve for x in mx = v
x = numpy.linalg.solve(m, v)
print(x)
print(m * x)

[[ 0.96521739]
 [ 0.17391304]
 [ 0.46086957]]
[[ 2.]
 [ 3.]
 [ 4.]]


### 3.11 随机选择

In [68]:
import random
values = [1, 2, 3, 4, 5, 6]
# 从序列中随机挑选出元素
print(random.choice(values))
# 取样出N个元素
print(random.sample(values, 2))

6
[3, 1]


In [70]:
# 在序列中原地打乱元素的顺序（洗牌）
random.shuffle(values)
print(values)

[2, 6, 5, 3, 1, 4]


In [72]:
# 产生随机数
print(random.randint(0,10))

2


In [73]:
# 产生0-1之间均匀分布的浮点数值
print(random.random())

0.355367160739974


In [74]:
# 得到由N个随机比特位所表示的整数
print(random.getrandbits(8))

48
