In [10]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
b
c.dtype
a.shape
c.shape = 4,3
c.shape = 2,-1
c
d = a.reshape(2,-1)
d

array([1, 2, 3, 4])

In [11]:
np.arange(0,1,0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [14]:
np.linspace(0,1,10,endpoint=False)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [2]:
import numpy as np
np.logspace(0,2,5)

array([   1.        ,    3.16227766,   10.        ,   31.6227766 ,  100.        ])

In [6]:
#frombuffer,fromstring,fromfile,fromfunction
def func(i):
    return i%4+1
np.fromfunction(func,(10,))

array([ 1.,  2.,  3.,  4.,  1.,  2.,  3.,  4.,  1.,  2.])

In [7]:
x = np.random.rand(10)
x[x>0.5]

array([ 0.65849861,  0.5848451 ,  0.69512125,  0.85476612,  0.63314085,
        0.64342209])

In [11]:
a = np.arange(0,60,10).reshape(-1,1) + np.arange(0,6)
print(a)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [12]:
a[(1,2,3),(2,3,4)]

array([12, 23, 34])

In [16]:
a[3:,[2,3,4]]

array([[32, 33, 34],
       [42, 43, 44],
       [52, 53, 54]])

In [23]:
mask = np.array([1,0,1,0,0,1],dtype=np.bool)
a[mask,2:4]

array([[ 2,  3],
       [22, 23],
       [52, 53]])

In [27]:
#结构数组
import numpy as np
persontype = np.dtype({
    'names':['name','age','weight'],
    'formats':['S32','i','f']
})

a = np.array([('Zhang',32,75.6),('Wang',24,'60.5')],dtype=persontype)
a

array([(b'Zhang', 32,  75.59999847), (b'Wang', 24,  60.5       )], 
      dtype=[('name', 'S32'), ('age', '<i4'), ('weight', '<f4')])