# universal function 

In [5]:
import numpy as np
x = np.linspace(0,2*np.pi,10)
y = np.sin(x)
y

array([  0.00000000e+00,   6.42787610e-01,   9.84807753e-01,
         8.66025404e-01,   3.42020143e-01,  -3.42020143e-01,
        -8.66025404e-01,  -9.84807753e-01,  -6.42787610e-01,
        -2.44929360e-16])

In [17]:
a = np.arange(0,4)
b = np.arange(1,5)
c=np.empty_like(a)
np.add(a,b,c)


array([ True,  True,  True,  True], dtype=bool)

In [20]:
a<b
np.logical_or(a==b,a<b)

array([ True,  True,  True,  True], dtype=bool)

In [28]:
#三角波函数，转换成ufunc函数
def triangle_wave(x,c,c0,hc):
    x = x-int(x)
    if x >= c:
        r = 0.0
    elif x<c0:
        r = x/c0*hc
    else:
        r = (c-x)/(c-c0)*hc
    return r
x = np.linspace(0,2,100)

triangle_ufunc1 = np.frompyfunc(triangle_wave,4,1)
y2 = triangle_ufunc1(x,0.6,0.4,1.0)

triangle_unfunc2 = np.frompyfunc(lambda x:triangle_wave(x,0.6,0.4,1.0),1,1)
y3 = triangle_unfunc2(x)

In [32]:
triangle_unfunc3 = np.vectorize(triangle_wave,otypes=[np.float])
y4 = triangle_unfunc3(x,0.6,0.4,1.0)
y4.dtype

dtype('float64')

In [35]:
import numpy as np
a = np.arange(12).reshape(2,3,2)
b = np.arange(12,24).reshape(2,2,3)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [36]:
b

array([[[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [37]:
c = np.dot(a,b)
c

array([[[[ 15,  16,  17],
         [ 21,  22,  23]],

        [[ 69,  74,  79],
         [ 99, 104, 109]],

        [[123, 132, 141],
         [177, 186, 195]]],


       [[[177, 190, 203],
         [255, 268, 281]],

        [[231, 248, 265],
         [333, 350, 367]],

        [[285, 306, 327],
         [411, 432, 453]]]])

In [61]:
import numpy as np
a = np.arange(4)
b = np.add.accumulate(a)
c = a + b
f = open('test.txt','wb')
for i in (a,b,c): 
    np.savetxt(f,i.reshape(1,-1),fmt='%d',delimiter='\t')
#np.savetxt(f,b,fmt='%d')
f.close()
a.shape

(4,)