In [6]:
import numpy as np

# multiply，对应位置相乘
x1 = [1,2,3]
x2 = [4,5,6]
print(np.multiply(x1,x2))
print(np.array(x1) * np.array(x2))

[ 4 10 18]
[ 4 10 18]


In [11]:
import numpy as np

# std标准差，var方差
b = [1,3,5,7,9]
print(np.var(b), np.std(b))
ll = [[1,2,3,4],[5,6,7,8]]
print(np.var(ll[0]))
print(np.var(ll, 0), np.var(ll, 1))

8.0 2.8284271247461903
1.25
[4. 4. 4. 4.] [1.25 1.25]


In [13]:
import numpy as np

# mean均值, sum求和
b = [1,3,5,7]
print(np.mean(b))
print(np.sum(b))

4.0
16


 样本均值$ \quad \overline X = \frac 1 N \sum_{i=1}^NX_i $  
   
 样本方差$ \quad S =\frac 1 {N-1} \sum_{i=1}^N(X_i-\overline X)^2 $
  
 样本协方差$ \quad C = \frac 1 {N-1} \sum_{i=1}^N(X_i-\overline X)(Y_i-\overline Y) $
 

In [57]:
import numpy as np
# cov协方差 ,样本方差是协方差中变量维数为1的特殊情况
# Cov(X,Y) = E[XY] - E[X]E[Y]
b = [1,3,5,7,9]
c = [-2,-4,-6,-8,-10]
print(np.cov(b))
print(np.sum((np.multiply(b,b))-np.mean(b)*np.mean(b))/4)

10.0
10.0


In [62]:
a = np.array([[1,2],
            [5,4],
            [8,10],
            [13,17]])
print(np.cov(a))

[[ 0.5 -0.5  1.   2. ]
 [-0.5  0.5 -1.  -2. ]
 [ 1.  -1.   2.   4. ]
 [ 2.  -2.   4.   8. ]]


In [64]:
import numpy as np

# corrcoef相关系数矩阵，两个向量的相似程度
vc = [1,2,3,0,8]
vb = [ 3,5,6,7,12]
print(np.corrcoef(vc,vb))
print(np.cov(vc,vb))

[[1.         0.82621109]
 [0.82621109 1.        ]]
[[ 9.7   8.65]
 [ 8.65 11.3 ]]


In [66]:
import numpy as np

# dot点积， vdot向量点积
a = [1,2,3]
b = [2,3,4]
print(np.dot(a,b))

20


In [84]:
import numpy as np

a = np.array([1,2,3])
b = np.array([2,3,4])
print(np.dot(a,b), a*b, np.multiply(a,b.T))

20 [ 2  6 12] [ 2  6 12]


In [89]:
import numpy as np

a = np.mat([1,2,3])
b = np.mat([2,3,4])
print(np.multiply(a,b),'\n' ,np.multiply(a,b.T),np.dot(a,b.T),a*b.T)

[[ 2  6 12]] 
 [[ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]] [[20]] [[20]]


In [113]:
dir(time)

['CLOCK_MONOTONIC',
 'CLOCK_MONOTONIC_RAW',
 'CLOCK_PROCESS_CPUTIME_ID',
 'CLOCK_REALTIME',
 'CLOCK_THREAD_CPUTIME_ID',
 '_STRUCT_TM_ITEMS',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'altzone',
 'asctime',
 'clock',
 'clock_getres',
 'clock_gettime',
 'clock_settime',
 'ctime',
 'daylight',
 'get_clock_info',
 'gmtime',
 'localtime',
 'mktime',
 'monotonic',
 'perf_counter',
 'process_time',
 'sleep',
 'strftime',
 'strptime',
 'struct_time',
 'time',
 'timezone',
 'tzname',
 'tzset']