In [9]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8],dtype=np.float)
c = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(b.dtype)
print(b)
print(a.shape,c.shape)
c.shape=(4,3)
print(c)
c

float64
[5. 6. 7. 8.]
(4,) (3, 4)
[[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  9 10]]


array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

arange函数类似于python的range函数，通过指定开始值、终值、和步长来创建一维数组，注意数组不包括终值

In [10]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

linspace函数通过指定开始值、终值和元素个数来创建一维数组，可通过endpoint关键字指定是否包括终值，缺省设置是包括终值

In [12]:
np.linspace(0,1,10,endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

logspace函数和linspace类似，不过它创建等比数列，下面的例子产生1（10^0）到100（10^2）、有20个元素的等比数列

In [13]:
np.logspace(0,2,20)

array([  1.        ,   1.27427499,   1.62377674,   2.06913808,
         2.6366509 ,   3.35981829,   4.2813324 ,   5.45559478,
         6.95192796,   8.8586679 ,  11.28837892,  14.38449888,
        18.32980711,  23.35721469,  29.76351442,  37.92690191,
        48.32930239,  61.58482111,  78.47599704, 100.        ])

zeros()、ones()、empty()可以创建指定形状和类型的数组

In [19]:
np.empty((2,3),np.int) #只分配内存，不对其进行初始化

array([[139852851423224, 139852874296432,               0],
       [              0,               0,               0]])

In [21]:
np.zeros((3,4),np.float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])